name: Deploy Todo Application
on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths: 
      - 'apps/server/**'
      - 'apps/web-todo/**'
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  checkout-prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

  build-deploy-web:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: checkout-prep
    steps:
      - name: Build React Application
        run: pnpm -r --filter=web-todo build

      - name: explore serve
        run: ls -l

      - name: Upload React Application
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./apps/web-todo/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
  
  build-deploy-server:
    runs-on: ubuntu-latest
    needs: checkout-prep

    steps:
      - name: Build Nest Application
        run: pnpm -r --filter=server build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Application
        run: pnpm --filter=server deploy:aws